server:
  port: 7002

spring:
  application:
    name: eureka-service
  security:
    user:
      name: felix
      password: 123456

eureka:
  client:
    register-with-eureka: true #是否注册到Eureka服务中
    fetch-registry: true #是否从Eureka服务中获取注册信息
    service-url: #Eureka客户端与服务端进行交互的地址
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:7000/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:7001/eureka/